events {
    worker_connections 1024;
}

http {
    # Define the custom JSON log format
    log_format hng_json_format escape=json
        '{'
            '"source_ip": "$remote_addr", '
            '"timestamp": "$time_local", '
            '"method": "$request_method", '
            '"path": "$request_uri", '
            '"status": "$status", '
            '"response_size": "$body_bytes_sent"'
        '}';

    # Tell Nginx to use this format and write to the shared volume path
    access_log /var/log/nginx/hng-access.log hng_json_format;

    server {
        listen 80;

        location / {
            proxy_pass http://nextcloud:80;
            
            # Ensure the real IP is passed to the backend
            proxy_set_header X-Forwarded-For $remote_addr;
            
            # Standard headers for proxying
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}